training:
  batch_size: 128
  n_epochs: 500000
  n_iters: 300001
  snapshot_freq: 5000
  snapshot_sampling: true
  anneal_power: 2
  log_all_sigmas: false

sampling:
  batch_size: 100
  data_init: false
  step_lr: 0.0000100098684
  n_steps_each: 5
  ckpt_id: 300000
  final_only: true
  fid: false
  denoise: true
  num_samples4fid: 10000
  inpainting: false
  interpolation: false
  n_interpolations: 15


test:
  begin_ckpt: 5000
  end_ckpt: 300001
  batch_size: 100

data:
  dataset: "unconditional_lambert"
  image_size: 1024
  image_size_feats: 6
  channels: 1
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: false
  rescaled: false
  num_workers: 32
  csv_file : '/project/erwin_763/Tpresser/github/ScoreNet/extended_mars_transfers/1024/csv/sample_initial_conditions_scaled.csv'
  root_dir : '/Users/tylerpresser/Documents/GitHub/ScoreNet/'


model:
  sigma_begin: 38
  num_classes: 310
  ema: true
  ema_rate: 0.999
  spec_norm: false
  sigma_dist: geometric
  sigma_end: 0.01
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 32

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0001
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001
